# 📘 NLP: Text Preprocessing

## 🔍 What is Text Preprocessing?

Text preprocessing is the process of converting raw, unstructured text into a clean and structured format suitable for analysis and machine learning. It involves various techniques to remove noise, standardize language, and extract useful components from text data.

---

## ❓ Why is Text Preprocessing Important?

- Real-world text contains noise: typos, punctuation, casing, extra spaces, and irrelevant words.
- Helps in reducing vocabulary size and improving model accuracy.
- Makes data uniform and ready for feature extraction or modeling.
- Removes inconsistencies that may confuse machine learning algorithms.

---

## 🧰 Libraries Commonly Used for Text Preprocessing

| Library | Purpose |
|--------|---------|
| **NLTK** (Natural Language Toolkit) | Offers tools for tokenization, stemming, lemmatization, and stopword removal |
| **spaCy** | Fast and production-ready NLP library with built-in preprocessing capabilities |
| **re** | Regular expressions, useful for cleaning text (e.g., removing special characters) |
| **string** | Built-in Python module, useful for handling punctuation |
| **TextBlob** | Simple API for text processing, includes lemmatization and sentiment analysis |
| **gensim** | Useful for topic modeling, also provides some preprocessing utilities |

---

## 🔄 Major Text Preprocessing Steps

### 1. ✂️ Tokenization

**Definition**: Tokenization is the process of breaking text into smaller units called tokens. These can be words, subwords, or sentences.

- **Sentence Tokenization**: Splits a paragraph into individual sentences.
  - Tools: NLTK (`sent_tokenize`), spaCy (`doc.sents`)
- **Word Tokenization**: Splits a sentence into words.
  - Tools: NLTK (`word_tokenize`), spaCy (`doc[i].text`)

**Example**:  
Text: "Text preprocessing is essential."  
Word Tokens: ['Text', 'preprocessing', 'is', 'essential', '.']

---

### 2. 🔡 Lowercasing

**Definition**: Converts all characters in the text to lowercase.

**Why**: Reduces redundancy by treating "Apple" and "apple" as the same word.

**Example**:  
['Apple', 'apple', 'APPLE'] → ['apple', 'apple', 'apple']

---

### 3. ❌ Removing Punctuation

**Definition**: Removes symbols like commas, periods, exclamation marks, etc.

**Why**: Punctuation usually does not add meaningful information for many NLP tasks.

**Tools**:  
- `string.punctuation` from Python’s built-in string library  
- `re` module using regular expressions

**Example**:  
"Hello, world!" → "Hello world"

---

### 4. 🛑 Stopword Removal

**Definition**: Stopwords are common words that do not carry significant meaning and are often removed to reduce noise.

**Examples of Stopwords**: is, am, are, the, in, on, and, or

**Tools**:  
- NLTK (`stopwords.words('english')`)  
- spaCy (`token.is_stop`)  
- gensim (`remove_stopwords`)

**Example**:  
Text: "This is a good movie"  
After stopword removal: "good movie"

---

### 5. 🌱 Stemming

**Definition**: Stemming reduces words to their root form by removing suffixes. It may not return valid dictionary words.

**Available Stemmers** in NLTK:
- **PorterStemmer**: Most commonly used, moderate stemming
- **LancasterStemmer**: More aggressive
- **SnowballStemmer**: An improved version of Porter, supports multiple languages

**Example**:  
"running", "runs", "ran" → "run"

**Note**: Stemming can result in over-stemming (e.g., "universities" → "univers")

---

### 6. 🍋 Lemmatization

**Definition**: Lemmatization also reduces words to their base form (lemma), but uses a dictionary and considers the part of speech.

**Difference from Stemming**:  
- Lemmatization is slower but more accurate.
- Lemmatization returns actual dictionary words.

**Available Lemmatizers**:
- **WordNetLemmatizer** (in NLTK)
- **spaCy built-in lemmatizer**
- **TextBlob lemmatizer**

**Example**:  
"running" (verb) → "run"  
"better" (adjective) → "good"

---

## 📋 Summary of Preprocessing Techniques

| Step | Description | Tools/Libraries |
|------|-------------|-----------------|
| Tokenization | Split text into words/sentences | NLTK, spaCy, TextBlob |
| Lowercasing | Convert all tokens to lowercase | Python built-in |
| Remove Punctuation | Delete special symbols | string, re |
| Stopword Removal | Remove common uninformative words | NLTK, spaCy, gensim |
| Stemming | Reduce word to root form (not always valid word) | Porter, Lancaster, Snowball |
| Lemmatization | Reduce word to base form using dictionary | WordNet, spaCy, TextBlob |

---

## ✅ Final Notes

- The choice of techniques depends on the NLP task.
- For rule-based or simple tasks, stemming may be enough.
- For semantic or deep models, lemmatization is preferred.
- Proper preprocessing leads to better accuracy, reduced noise, and lower dimensionality in models.

# Install the Required Libraries

In [3]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\waqar\anaconda3\lib\site-packages (3.8.1)
Requirement already satisfied: click in c:\users\waqar\anaconda3\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\waqar\anaconda3\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\waqar\anaconda3\lib\site-packages (from nltk) (2023.10.3)
Requirement already satisfied: tqdm in c:\users\waqar\anaconda3\lib\site-packages (from nltk) (4.66.4)
Requirement already satisfied: colorama in c:\users\waqar\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

# Import the Required Libraries

In [5]:
!pip install contractions

Requirement already satisfied: contractions in c:\users\waqar\anaconda3\lib\site-packages (0.1.73)
Requirement already satisfied: textsearch>=0.0.21 in c:\users\waqar\anaconda3\lib\site-packages (from contractions) (0.0.24)
Requirement already satisfied: anyascii in c:\users\waqar\anaconda3\lib\site-packages (from textsearch>=0.0.21->contractions) (0.3.2)
Requirement already satisfied: pyahocorasick in c:\users\waqar\anaconda3\lib\site-packages (from textsearch>=0.0.21->contractions) (2.1.0)

In [1]:
import pandas as pd
import nltk

from nltk.corpus import stopwords

from nltk.tokenize import word_tokenize

from nltk.stem import WordNetLemmatizer, PorterStemmer


import string

import re 

    
import contractions

# Download necessary NLTK data if not already available

In [3]:

nltk.download('stopwords')

# Printing the stopwords in English
stop_words = set(stopwords.words('english'))
print("Stop words:", stop_words)

Stop words: {'but', "you'd", 'having', 'does', 'from', 'until', 'been', 'o', 'was', 'myself', 'during', 'needn', 'up', 'only', 'd', 've', 'the', 'on', 'hasn', 'shan', 'being', 'in', 'at', 'because', 'our', 'mightn', 'why', 'some', "it'd", "isn't", 'to', 'where', 'ma', 'any', 'has', 'before', 'wouldn', 'won', 'it', 'and', 'she', "we'll", 'nor', 'as', "i'll", 'few', 'were', 'hadn', 'don', "she'll", 'with', 'did', "doesn't", "it's", 'ours', 'themselves', "they'll", 'these', 'hers', 'no', 'all', 'out', 'am', 'more', 'my', 'if', 'aren', 'isn', 'other', 'we', 'what', 'wasn', 'own', 'himself', "haven't", "it'll", 'ourselves', "i've", 'such', 'who', 'when', 'than', 'him', 'this', 'just', "she's", 'his', 'while', 'yours', 'herself', "he'd", 'a', 'further', 'now', "mustn't", 'about', "hasn't", "won't", 'between', 'so', 'they', 't', 'haven', 'couldn', 'for', 'me', 're', "weren't", 'm', 'are', 'those', 'mustn', 'both', 'your', "we've", 'under', "we're", 'an', 'same', "she'd", "they're", 'can', "didn't", "needn't", 'over', "should've", 'doesn', 'which', "he's", 'have', 'below', 'its', "you'll", 'do', "mightn't", 'you', 'will', 'her', 'here', "wouldn't", 'yourself', 'each', 'be', "you're", "he'll", 'once', 'had', "that'll", 's', "don't", 'most', 'he', "we'd", "aren't", "they'd", "shan't", "i'm", 'of', 'yourselves', 'through', 'too', "you've", 'doing', 'whom', 'y', 'them', 'or', 'itself', 'll', "wasn't", 'against', 'is', 'then', 'very', 'by', 'again', 'didn', 'shouldn', "shouldn't", "hadn't", 'their', 'should', "i'd", 'that', 'how', 'i', 'into', 'ain', 'not', 'weren', 'after', "couldn't", "they've", 'there', 'theirs', 'down', 'off', 'above'}

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\waqar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [4]:
nltk.download('punkt')

nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\waqar\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\waqar\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

# Create a Dummy Dataset

In [6]:
# Create the DataFrame with terrorism-related data
data = {
    'ID': [1, 2, 3, 4, 5],
    'Text': [
        "A bombing occurred in downtown Baghdad. Resulting in several casualties and injuries.",
        "The terrorist group claimed responsibility for the attack on the military checkpoint.",
        "Security forces arrested suspects linked to a plot targeting public transportation.",
        "The use of improvised explosive devices has increased in recent insurgent activities.",
        "Counter-terrorism units conducted a raid on a suspected militant hideout in the region."
    ]
}


df = pd.DataFrame(data)
# Adjusting pandas options to display full content in the dataframe
pd.set_option('display.max_colwidth', None)

df

,ID,Text
0,1,A bombing occurred in downtown Baghdad. Resulting in several casualties and injuries.
1,2,The terrorist group claimed responsibility for the attack on the military checkpoint.
2,3,Security forces arrested suspects linked to a plot targeting public transportation.
3,4,The use of improvised explosive devices has increased in recent insurgent activities.
4,5,Counter-terrorism units conducted a raid on a suspected militant hideout in the region.

In [7]:
df

,ID,Text
0,1,A bombing occurred in downtown Baghdad. Resulting in several casualties and injuries.
1,2,The terrorist group claimed responsibility for the attack on the military checkpoint.
2,3,Security forces arrested suspects linked to a plot targeting public transportation.
3,4,The use of improvised explosive devices has increased in recent insurgent activities.
4,5,Counter-terrorism units conducted a raid on a suspected militant hideout in the region.

In [8]:
# Save to CSV
df.to_csv("counter_terrorism_dataset.csv", index=False)

In [9]:
# Read the CSV back
df = pd.read_csv("counter_terrorism_dataset.csv")

df

,ID,Text
0,1,A bombing occurred in downtown Baghdad. Resulting in several casualties and injuries.
1,2,The terrorist group claimed responsibility for the attack on the military checkpoint.
2,3,Security forces arrested suspects linked to a plot targeting public transportation.
3,4,The use of improvised explosive devices has increased in recent insurgent activities.
4,5,Counter-terrorism units conducted a raid on a suspected militant hideout in the region.

In [10]:
df['Text']

0      A bombing occurred in downtown Baghdad. Resulting in several casualties and injuries.
1      The terrorist group claimed responsibility for the attack on the military checkpoint.
2        Security forces arrested suspects linked to a plot targeting public transportation.
3      The use of improvised explosive devices has increased in recent insurgent activities.
4    Counter-terrorism units conducted a raid on a suspected militant hideout in the region.
Name: Text, dtype: object

In [11]:
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize

# Download NLTK tokenizers (only once)
nltk.download('punkt')

# Apply tokenization
df['sentences'] = df['Text'].apply(sent_tokenize)
df

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\waqar\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

,ID,Text,sentences
0,1,A bombing occurred in downtown Baghdad. Resulting in several casualties and injuries.,"[A bombing occurred in downtown Baghdad., Resulting in several casualties and injuries.]"
1,2,The terrorist group claimed responsibility for the attack on the military checkpoint.,[The terrorist group claimed responsibility for the attack on the military checkpoint.]
2,3,Security forces arrested suspects linked to a plot targeting public transportation.,[Security forces arrested suspects linked to a plot targeting public transportation.]
3,4,The use of improvised explosive devices has increased in recent insurgent activities.,[The use of improvised explosive devices has increased in recent insurgent activities.]
4,5,Counter-terrorism units conducted a raid on a suspected militant hideout in the region.,[Counter-terrorism units conducted a raid on a suspected militant hideout in the region.]

In [12]:
df['tokens'] = df['Text'].apply(word_tokenize)

df

,ID,Text,sentences,tokens
0,1,A bombing occurred in downtown Baghdad. Resulting in several casualties and injuries.,"[A bombing occurred in downtown Baghdad., Resulting in several casualties and injuries.]","[A, bombing, occurred, in, downtown, Baghdad, ., Resulting, in, several, casualties, and, injuries, .]"
1,2,The terrorist group claimed responsibility for the attack on the military checkpoint.,[The terrorist group claimed responsibility for the attack on the military checkpoint.],"[The, terrorist, group, claimed, responsibility, for, the, attack, on, the, military, checkpoint, .]"
2,3,Security forces arrested suspects linked to a plot targeting public transportation.,[Security forces arrested suspects linked to a plot targeting public transportation.],"[Security, forces, arrested, suspects, linked, to, a, plot, targeting, public, transportation, .]"
3,4,The use of improvised explosive devices has increased in recent insurgent activities.,[The use of improvised explosive devices has increased in recent insurgent activities.],"[The, use, of, improvised, explosive, devices, has, increased, in, recent, insurgent, activities, .]"
4,5,Counter-terrorism units conducted a raid on a suspected militant hideout in the region.,[Counter-terrorism units conducted a raid on a suspected militant hideout in the region.],"[Counter-terrorism, units, conducted, a, raid, on, a, suspected, militant, hideout, in, the, region, .]"

In [13]:
# Show example
for idx, row in df.iterrows():
    print(f"\n🔹 Title: {row['Text']}")
    print("📌 Sentences:", row['sentences'])
    print("📌 Word Tokens:", row['tokens'])

🔹 Title: A bombing occurred in downtown Baghdad. Resulting in several casualties and injuries.
📌 Sentences: ['A bombing occurred in downtown Baghdad.', 'Resulting in several casualties and injuries.']
📌 Word Tokens: ['A', 'bombing', 'occurred', 'in', 'downtown', 'Baghdad', '.', 'Resulting', 'in', 'several', 'casualties', 'and', 'injuries', '.']

🔹 Title: The terrorist group claimed responsibility for the attack on the military checkpoint.
📌 Sentences: ['The terrorist group claimed responsibility for the attack on the military checkpoint.']
📌 Word Tokens: ['The', 'terrorist', 'group', 'claimed', 'responsibility', 'for', 'the', 'attack', 'on', 'the', 'military', 'checkpoint', '.']

🔹 Title: Security forces arrested suspects linked to a plot targeting public transportation.
📌 Sentences: ['Security forces arrested suspects linked to a plot targeting public transportation.']
📌 Word Tokens: ['Security', 'forces', 'arrested', 'suspects', 'linked', 'to', 'a', 'plot', 'targeting', 'public', 'transportation', '.']

🔹 Title: The use of improvised explosive devices has increased in recent insurgent activities.
📌 Sentences: ['The use of improvised explosive devices has increased in recent insurgent activities.']
📌 Word Tokens: ['The', 'use', 'of', 'improvised', 'explosive', 'devices', 'has', 'increased', 'in', 'recent', 'insurgent', 'activities', '.']

🔹 Title: Counter-terrorism units conducted a raid on a suspected militant hideout in the region.
📌 Sentences: ['Counter-terrorism units conducted a raid on a suspected militant hideout in the region.']
📌 Word Tokens: ['Counter-terrorism', 'units', 'conducted', 'a', 'raid', 'on', 'a', 'suspected', 'militant', 'hideout', 'in', 'the', 'region', '.']

In [14]:
df

,ID,Text,sentences,tokens
0,1,A bombing occurred in downtown Baghdad. Resulting in several casualties and injuries.,"[A bombing occurred in downtown Baghdad., Resulting in several casualties and injuries.]","[A, bombing, occurred, in, downtown, Baghdad, ., Resulting, in, several, casualties, and, injuries, .]"
1,2,The terrorist group claimed responsibility for the attack on the military checkpoint.,[The terrorist group claimed responsibility for the attack on the military checkpoint.],"[The, terrorist, group, claimed, responsibility, for, the, attack, on, the, military, checkpoint, .]"
2,3,Security forces arrested suspects linked to a plot targeting public transportation.,[Security forces arrested suspects linked to a plot targeting public transportation.],"[Security, forces, arrested, suspects, linked, to, a, plot, targeting, public, transportation, .]"
3,4,The use of improvised explosive devices has increased in recent insurgent activities.,[The use of improvised explosive devices has increased in recent insurgent activities.],"[The, use, of, improvised, explosive, devices, has, increased, in, recent, insurgent, activities, .]"
4,5,Counter-terrorism units conducted a raid on a suspected militant hideout in the region.,[Counter-terrorism units conducted a raid on a suspected militant hideout in the region.],"[Counter-terrorism, units, conducted, a, raid, on, a, suspected, militant, hideout, in, the, region, .]"

In [15]:
df['tokens']

0     [A, bombing, occurred, in, downtown, Baghdad, ., Resulting, in, several, casualties, and, injuries, .]
1       [The, terrorist, group, claimed, responsibility, for, the, attack, on, the, military, checkpoint, .]
2          [Security, forces, arrested, suspects, linked, to, a, plot, targeting, public, transportation, .]
3       [The, use, of, improvised, explosive, devices, has, increased, in, recent, insurgent, activities, .]
4    [Counter-terrorism, units, conducted, a, raid, on, a, suspected, militant, hideout, in, the, region, .]
Name: tokens, dtype: object

# Function to remove punctuation

In [17]:
import string
# Define the function to remove punctuation
def remove_punctuation(tokens):
    return [word for word in tokens if word not in string.punctuation]

# Apply the function to the 'tokens' column 
df['cleantokens'] = df['tokens'].apply(remove_punctuation)
df

,ID,Text,sentences,tokens,cleantokens
0,1,A bombing occurred in downtown Baghdad. Resulting in several casualties and injuries.,"[A bombing occurred in downtown Baghdad., Resulting in several casualties and injuries.]","[A, bombing, occurred, in, downtown, Baghdad, ., Resulting, in, several, casualties, and, injuries, .]","[A, bombing, occurred, in, downtown, Baghdad, Resulting, in, several, casualties, and, injuries]"
1,2,The terrorist group claimed responsibility for the attack on the military checkpoint.,[The terrorist group claimed responsibility for the attack on the military checkpoint.],"[The, terrorist, group, claimed, responsibility, for, the, attack, on, the, military, checkpoint, .]","[The, terrorist, group, claimed, responsibility, for, the, attack, on, the, military, checkpoint]"
2,3,Security forces arrested suspects linked to a plot targeting public transportation.,[Security forces arrested suspects linked to a plot targeting public transportation.],"[Security, forces, arrested, suspects, linked, to, a, plot, targeting, public, transportation, .]","[Security, forces, arrested, suspects, linked, to, a, plot, targeting, public, transportation]"
3,4,The use of improvised explosive devices has increased in recent insurgent activities.,[The use of improvised explosive devices has increased in recent insurgent activities.],"[The, use, of, improvised, explosive, devices, has, increased, in, recent, insurgent, activities, .]","[The, use, of, improvised, explosive, devices, has, increased, in, recent, insurgent, activities]"
4,5,Counter-terrorism units conducted a raid on a suspected militant hideout in the region.,[Counter-terrorism units conducted a raid on a suspected militant hideout in the region.],"[Counter-terrorism, units, conducted, a, raid, on, a, suspected, militant, hideout, in, the, region, .]","[Counter-terrorism, units, conducted, a, raid, on, a, suspected, militant, hideout, in, the, region]"

# Removal of Stopwords

In [19]:
import pandas as pd
from nltk.corpus import stopwords

# Make sure you have the stopwords downloaded
# import nltk
# nltk.download('stopwords')

# Get the set of English stopwords
stop_words = set(stopwords.words('english'))
stop_words

# Define a function to remove stopwords
def remove_stopwords(tokens):
    return [word for word in tokens if word.lower() not in stop_words]

# Apply the function to the 'tokens' column
df['cleantokens'] = df['cleantokens'].apply(remove_stopwords)
df

,ID,Text,sentences,tokens,cleantokens
0,1,A bombing occurred in downtown Baghdad. Resulting in several casualties and injuries.,"[A bombing occurred in downtown Baghdad., Resulting in several casualties and injuries.]","[A, bombing, occurred, in, downtown, Baghdad, ., Resulting, in, several, casualties, and, injuries, .]","[bombing, occurred, downtown, Baghdad, Resulting, several, casualties, injuries]"
1,2,The terrorist group claimed responsibility for the attack on the military checkpoint.,[The terrorist group claimed responsibility for the attack on the military checkpoint.],"[The, terrorist, group, claimed, responsibility, for, the, attack, on, the, military, checkpoint, .]","[terrorist, group, claimed, responsibility, attack, military, checkpoint]"
2,3,Security forces arrested suspects linked to a plot targeting public transportation.,[Security forces arrested suspects linked to a plot targeting public transportation.],"[Security, forces, arrested, suspects, linked, to, a, plot, targeting, public, transportation, .]","[Security, forces, arrested, suspects, linked, plot, targeting, public, transportation]"
3,4,The use of improvised explosive devices has increased in recent insurgent activities.,[The use of improvised explosive devices has increased in recent insurgent activities.],"[The, use, of, improvised, explosive, devices, has, increased, in, recent, insurgent, activities, .]","[use, improvised, explosive, devices, increased, recent, insurgent, activities]"
4,5,Counter-terrorism units conducted a raid on a suspected militant hideout in the region.,[Counter-terrorism units conducted a raid on a suspected militant hideout in the region.],"[Counter-terrorism, units, conducted, a, raid, on, a, suspected, militant, hideout, in, the, region, .]","[Counter-terrorism, units, conducted, raid, suspected, militant, hideout, region]"

In [20]:
import pandas as pd
from nltk.stem import WordNetLemmatizer

# Make sure you have the WordNet data downloaded
# import nltk
# nltk.download('wordnet')
# nltk.download('omw-1.4')

# Initialize the lemmatizer
lemmatizer = WordNetLemmatizer()

# Define the lemmatization function
def lemmatize_text(tokens):
    return [lemmatizer.lemmatize(word) for word in tokens]

# Apply it to the 'tokens' column
df['Lemmatokens'] = df['cleantokens'].apply(lemmatize_text)
df

,ID,Text,sentences,tokens,cleantokens,Lemmatokens
0,1,A bombing occurred in downtown Baghdad. Resulting in several casualties and injuries.,"[A bombing occurred in downtown Baghdad., Resulting in several casualties and injuries.]","[A, bombing, occurred, in, downtown, Baghdad, ., Resulting, in, several, casualties, and, injuries, .]","[bombing, occurred, downtown, Baghdad, Resulting, several, casualties, injuries]","[bombing, occurred, downtown, Baghdad, Resulting, several, casualty, injury]"
1,2,The terrorist group claimed responsibility for the attack on the military checkpoint.,[The terrorist group claimed responsibility for the attack on the military checkpoint.],"[The, terrorist, group, claimed, responsibility, for, the, attack, on, the, military, checkpoint, .]","[terrorist, group, claimed, responsibility, attack, military, checkpoint]","[terrorist, group, claimed, responsibility, attack, military, checkpoint]"
2,3,Security forces arrested suspects linked to a plot targeting public transportation.,[Security forces arrested suspects linked to a plot targeting public transportation.],"[Security, forces, arrested, suspects, linked, to, a, plot, targeting, public, transportation, .]","[Security, forces, arrested, suspects, linked, plot, targeting, public, transportation]","[Security, force, arrested, suspect, linked, plot, targeting, public, transportation]"
3,4,The use of improvised explosive devices has increased in recent insurgent activities.,[The use of improvised explosive devices has increased in recent insurgent activities.],"[The, use, of, improvised, explosive, devices, has, increased, in, recent, insurgent, activities, .]","[use, improvised, explosive, devices, increased, recent, insurgent, activities]","[use, improvised, explosive, device, increased, recent, insurgent, activity]"
4,5,Counter-terrorism units conducted a raid on a suspected militant hideout in the region.,[Counter-terrorism units conducted a raid on a suspected militant hideout in the region.],"[Counter-terrorism, units, conducted, a, raid, on, a, suspected, militant, hideout, in, the, region, .]","[Counter-terrorism, units, conducted, raid, suspected, militant, hideout, region]","[Counter-terrorism, unit, conducted, raid, suspected, militant, hideout, region]"

In [21]:
import pandas as pd
from nltk.stem import PorterStemmer

# Initialize the stemmer
stemmer = PorterStemmer()

# Define the stemming function
def stem_text(tokens):
    return [stemmer.stem(word) for word in tokens]

# Apply it to the 'tokens' column
df['Stemtokens'] = df['cleantokens'].apply(stem_text)
df

,ID,Text,sentences,tokens,cleantokens,Lemmatokens,Stemtokens
0,1,A bombing occurred in downtown Baghdad. Resulting in several casualties and injuries.,"[A bombing occurred in downtown Baghdad., Resulting in several casualties and injuries.]","[A, bombing, occurred, in, downtown, Baghdad, ., Resulting, in, several, casualties, and, injuries, .]","[bombing, occurred, downtown, Baghdad, Resulting, several, casualties, injuries]","[bombing, occurred, downtown, Baghdad, Resulting, several, casualty, injury]","[bomb, occur, downtown, baghdad, result, sever, casualti, injuri]"
1,2,The terrorist group claimed responsibility for the attack on the military checkpoint.,[The terrorist group claimed responsibility for the attack on the military checkpoint.],"[The, terrorist, group, claimed, responsibility, for, the, attack, on, the, military, checkpoint, .]","[terrorist, group, claimed, responsibility, attack, military, checkpoint]","[terrorist, group, claimed, responsibility, attack, military, checkpoint]","[terrorist, group, claim, respons, attack, militari, checkpoint]"
2,3,Security forces arrested suspects linked to a plot targeting public transportation.,[Security forces arrested suspects linked to a plot targeting public transportation.],"[Security, forces, arrested, suspects, linked, to, a, plot, targeting, public, transportation, .]","[Security, forces, arrested, suspects, linked, plot, targeting, public, transportation]","[Security, force, arrested, suspect, linked, plot, targeting, public, transportation]","[secur, forc, arrest, suspect, link, plot, target, public, transport]"
3,4,The use of improvised explosive devices has increased in recent insurgent activities.,[The use of improvised explosive devices has increased in recent insurgent activities.],"[The, use, of, improvised, explosive, devices, has, increased, in, recent, insurgent, activities, .]","[use, improvised, explosive, devices, increased, recent, insurgent, activities]","[use, improvised, explosive, device, increased, recent, insurgent, activity]","[use, improvis, explos, devic, increas, recent, insurg, activ]"
4,5,Counter-terrorism units conducted a raid on a suspected militant hideout in the region.,[Counter-terrorism units conducted a raid on a suspected militant hideout in the region.],"[Counter-terrorism, units, conducted, a, raid, on, a, suspected, militant, hideout, in, the, region, .]","[Counter-terrorism, units, conducted, raid, suspected, militant, hideout, region]","[Counter-terrorism, unit, conducted, raid, suspected, militant, hideout, region]","[counter-terror, unit, conduct, raid, suspect, milit, hideout, region]"

In [22]:
# Define the function to convert tokens to lowercase
def lowercase_tokens(tokens):
    return [word.lower() for word in tokens]

# Apply the function to the 'tokens' column
df['lowercasetokens'] = df['cleantokens'].apply(lowercase_tokens)
df

,ID,Text,sentences,tokens,cleantokens,Lemmatokens,Stemtokens,lowercasetokens
0,1,A bombing occurred in downtown Baghdad. Resulting in several casualties and injuries.,"[A bombing occurred in downtown Baghdad., Resulting in several casualties and injuries.]","[A, bombing, occurred, in, downtown, Baghdad, ., Resulting, in, several, casualties, and, injuries, .]","[bombing, occurred, downtown, Baghdad, Resulting, several, casualties, injuries]","[bombing, occurred, downtown, Baghdad, Resulting, several, casualty, injury]","[bomb, occur, downtown, baghdad, result, sever, casualti, injuri]","[bombing, occurred, downtown, baghdad, resulting, several, casualties, injuries]"
1,2,The terrorist group claimed responsibility for the attack on the military checkpoint.,[The terrorist group claimed responsibility for the attack on the military checkpoint.],"[The, terrorist, group, claimed, responsibility, for, the, attack, on, the, military, checkpoint, .]","[terrorist, group, claimed, responsibility, attack, military, checkpoint]","[terrorist, group, claimed, responsibility, attack, military, checkpoint]","[terrorist, group, claim, respons, attack, militari, checkpoint]","[terrorist, group, claimed, responsibility, attack, military, checkpoint]"
2,3,Security forces arrested suspects linked to a plot targeting public transportation.,[Security forces arrested suspects linked to a plot targeting public transportation.],"[Security, forces, arrested, suspects, linked, to, a, plot, targeting, public, transportation, .]","[Security, forces, arrested, suspects, linked, plot, targeting, public, transportation]","[Security, force, arrested, suspect, linked, plot, targeting, public, transportation]","[secur, forc, arrest, suspect, link, plot, target, public, transport]","[security, forces, arrested, suspects, linked, plot, targeting, public, transportation]"
3,4,The use of improvised explosive devices has increased in recent insurgent activities.,[The use of improvised explosive devices has increased in recent insurgent activities.],"[The, use, of, improvised, explosive, devices, has, increased, in, recent, insurgent, activities, .]","[use, improvised, explosive, devices, increased, recent, insurgent, activities]","[use, improvised, explosive, device, increased, recent, insurgent, activity]","[use, improvis, explos, devic, increas, recent, insurg, activ]","[use, improvised, explosive, devices, increased, recent, insurgent, activities]"
4,5,Counter-terrorism units conducted a raid on a suspected militant hideout in the region.,[Counter-terrorism units conducted a raid on a suspected militant hideout in the region.],"[Counter-terrorism, units, conducted, a, raid, on, a, suspected, militant, hideout, in, the, region, .]","[Counter-terrorism, units, conducted, raid, suspected, militant, hideout, region]","[Counter-terrorism, unit, conducted, raid, suspected, militant, hideout, region]","[counter-terror, unit, conduct, raid, suspect, milit, hideout, region]","[counter-terrorism, units, conducted, raid, suspected, militant, hideout, region]"

In [24]:
# Define the function to join tokens into a single string
def join_tokens(tokens):
    return ' '.join(tokens)

# Apply the function to create a new 'clean_text' column
df['clean_Lemma_text'] = df['lowercasetokens'].apply(join_tokens)
df

,ID,Text,sentences,tokens,cleantokens,Lemmatokens,Stemtokens,lowercasetokens,clean_Lemma_text
0,1,A bombing occurred in downtown Baghdad. Resulting in several casualties and injuries.,"[A bombing occurred in downtown Baghdad., Resulting in several casualties and injuries.]","[A, bombing, occurred, in, downtown, Baghdad, ., Resulting, in, several, casualties, and, injuries, .]","[bombing, occurred, downtown, Baghdad, Resulting, several, casualties, injuries]","[bombing, occurred, downtown, Baghdad, Resulting, several, casualty, injury]","[bomb, occur, downtown, baghdad, result, sever, casualti, injuri]","[bombing, occurred, downtown, baghdad, resulting, several, casualties, injuries]",bombing occurred downtown baghdad resulting several casualties injuries
1,2,The terrorist group claimed responsibility for the attack on the military checkpoint.,[The terrorist group claimed responsibility for the attack on the military checkpoint.],"[The, terrorist, group, claimed, responsibility, for, the, attack, on, the, military, checkpoint, .]","[terrorist, group, claimed, responsibility, attack, military, checkpoint]","[terrorist, group, claimed, responsibility, attack, military, checkpoint]","[terrorist, group, claim, respons, attack, militari, checkpoint]","[terrorist, group, claimed, responsibility, attack, military, checkpoint]",terrorist group claimed responsibility attack military checkpoint
2,3,Security forces arrested suspects linked to a plot targeting public transportation.,[Security forces arrested suspects linked to a plot targeting public transportation.],"[Security, forces, arrested, suspects, linked, to, a, plot, targeting, public, transportation, .]","[Security, forces, arrested, suspects, linked, plot, targeting, public, transportation]","[Security, force, arrested, suspect, linked, plot, targeting, public, transportation]","[secur, forc, arrest, suspect, link, plot, target, public, transport]","[security, forces, arrested, suspects, linked, plot, targeting, public, transportation]",security forces arrested suspects linked plot targeting public transportation
3,4,The use of improvised explosive devices has increased in recent insurgent activities.,[The use of improvised explosive devices has increased in recent insurgent activities.],"[The, use, of, improvised, explosive, devices, has, increased, in, recent, insurgent, activities, .]","[use, improvised, explosive, devices, increased, recent, insurgent, activities]","[use, improvised, explosive, device, increased, recent, insurgent, activity]","[use, improvis, explos, devic, increas, recent, insurg, activ]","[use, improvised, explosive, devices, increased, recent, insurgent, activities]",use improvised explosive devices increased recent insurgent activities
4,5,Counter-terrorism units conducted a raid on a suspected militant hideout in the region.,[Counter-terrorism units conducted a raid on a suspected militant hideout in the region.],"[Counter-terrorism, units, conducted, a, raid, on, a, suspected, militant, hideout, in, the, region, .]","[Counter-terrorism, units, conducted, raid, suspected, militant, hideout, region]","[Counter-terrorism, unit, conducted, raid, suspected, militant, hideout, region]","[counter-terror, unit, conduct, raid, suspect, milit, hideout, region]","[counter-terrorism, units, conducted, raid, suspected, militant, hideout, region]",counter-terrorism units conducted raid suspected militant hideout region

In [43]:
# Save to CSV
df.to_csv("cleaned_counter_terrorism_dataset.csv", index=False)